### ISSUE TITLE
Makefile:2608: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by hrvojegolcic** [espeak-ng/espeak-ng#1035]
I had limited permissions on my linux shared hosting server so I had to build it manually.
After entering the following commands:

```
git clone https://github.com/espeak-ng/espeak-ng.git
cd espeak-ng
./autogen.sh
./configure --prefix=/var/home/my-user/my-apps
make
```

The following error occurred: 

> Makefile:2608: *** missing separator.  Stop.

The workaround was simply to comment out the line 2608 from `Makefile`

> #docs_MARKDOWN != ls docs/*.md docs/*/*.md docs/*/*/*.md

And that allowed me to proceed with

```
make
make install
```

Not sure if I did something wrong or it's some kind of a bug, but might be worth to look into. 
Thanks!

**Comment by sthibaul** [comment]
Please paste the generated `Makefile` file so we can see what is at line 2608

**Comment by hrvojegolcic** [comment]
Hey! Sadly that was reported 4 months ago I do not have any installation files anymore, only `bin`, `lib` etc., if something from there can be useful let me know.

**Comment by Zhuoyuan1** [comment]
I have the same problem but at line 2640 in Makefile
[Makefile.txt](https://github.com/espeak-ng/espeak-ng/files/10694365/Makefile.txt)

**Comment by sthibaul** [comment]
can you try to rather put

```
docs_MARKDOWN = $(wildcard docs/*.md docs/*/*.md docs/*/*/*.md)
```

**Comment by Zhuoyuan1** [comment]
> can you try to rather put
> 
> ```
> docs_MARKDOWN = $(wildcard docs/*.md docs/*/*.md docs/*/*/*.md)
> ```

After modify it，it worked and no error occurred.

**Comment by sthibaul** [comment]
Ok, so that got fixed by 7954418b8874e0430d19eecec8d300eddddac169

**Comment by Zhuoyuan1** [comment]
This bug is not fixed.
The content of the `makefile.am` of the `master` branch is correct, but after execute `sh ./autogen.sh` , content of `makefile.am` is overwrittened

**Comment by sthibaul** [comment]
?? `autogen.sh` does *not* modify `Makefile.am`

**Comment by Zhuoyuan1** [comment]
Sorry, my mistake.
