### ISSUE TITLE
Turkish pronunciation problems

### ISSUE THREAD

**Issue by burakyuksek** [espeak-ng/espeak-ng#152]
Hello,
I have a few problems to report with the Turkish language:
1. Words that repeat a silent letter twice has the first instance of the letter muted. For example, in the word gitti, the first t needs to be muted.
2. The letters x, q and w are not pronounced correctly. X needs to be pronounced as iks rather than eks, w should be pronounced as çift v rather than duble v because duble is not a Turkish word, and the letter q  needs to be  pronounced as kyu rather than kve.
3. Words like sertifika and dakika should have the k a bit thicker.

**Comment by ValdisVitolins** [comment]
Fixed in https://github.com/ValdisVitolins/espeak-ng/commit/8ee1b6cbd3a90dba38609c332e9824c7a2f24e95
If [Test version](http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-X&text=x%20q%20w.%20sertifika%20dakika.) sounds OK, you can close this issue.

**Comment by burakyuksek** [comment]
It pronounces w as çift. It should be pronounced as çift v. Also words like etti, gitti are still not fixed. q, Dakika and sertifika sound fine.
23.09.2016 00:52 tarihinde Valdis Vitolins yazdı:

Fixed in ValdisVitolins@8ee1b6c<https://github.com/ValdisVitolins/espeak-ng/commit/8ee1b6cbd3a90dba38609c332e9824c7a2f24e95>
If Test version<http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-X&text=x%20q%20w.%20sertifika%20dakika.> sounds OK, you can close this issue.

**Comment by ValdisVitolins** [comment]
How it is [now](http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-x&text=www.+gitti.&formmethod=get)?

**Comment by burakyuksek** [comment]
It's fixed with the letter t now. If you can make the same thing with b, c, ç, d, g, k,, p that would be a lot better. Thank you very much.
24.09.2016 01:40 tarihinde Valdis Vitolins yazdı:

How it is now<http://odo.lv/Espeak?eslang=-vtr&speed=160&output=-w&debug=-x&text=www.+gitti.&formmethod=get>?

**Comment by ValdisVitolins** [comment]
Implemented in commit https://github.com/ValdisVitolins/espeak-ng/commit/26b9099e6faf689b1591055c12ba0f671cad610f 
You can check it [here](http://odo.lv/Espeak).

**Comment by burakyuksek** [comment]
Thank you, all of the letters are fine except p. Can you fix that too? I typed that in the pervious response but you probably missed it. I'm sorry if I'm bothering you.

24.09.2016 14:40 tarihinde Valdis Vitolins yazdı:

Implemented in commit ValdisVitolins@26b9099<https://github.com/ValdisVitolins/espeak-ng/commit/26b9099e6faf689b1591055c12ba0f671cad610f>
You can check it here<http://odo.lv/Espeak>.

**Comment by rhdunn** [comment]
I've corrected `p` when merging the changes. You'll have to wait for Valdis to build it on his test server.

**Comment by ValdisVitolins** [comment]
Thanks, Reece. I've pulled your changes and updated test server too.
Burakyuksek, you can check if these changes are OK.
