### ISSUE TITLE
problems with russian language

### ISSUE THREAD

**Issue by beqabeqa473** [espeak-ng/espeak-ng#474]
hello.

with recent changes with russian language pronunciation of several words were changed.
for example word "общение" letter щ sch is incorrectly pronounced.

letters when typing is also pronounced incorrectly, they are short
for example с б в ж к
letter л is very soft.

i have a question
why person who has no knowledge of this language such as @valdisvi is changing so serious things?
if he had, these mistakes which makes synthesizer usable in russian language never be existed.

please revert changes or fix them.

thanks.

**Comment by valdisvi** [comment]
beqabeqa473,

it happens to be, I know Russian very well. Because of russification policy of Soviet  Latvia, I learned Russian as my 2nd language around year 7. Later, because of militarization of science in Soviet times I learned theoretical mechanics, radio electronics and nuclear physics only from Russian literature. I not only learned, but passed my car driving license exam in Russian, because Latvian groups were overbooked ;-) I have worked in St. Petersburg for several months in branch of Exigen Services, and I have worked about 1 year for eGlobal, which was Russian company moved from Tambov to Riga. Also there official and conversational language was Russian. And even now, when I teach programming for new employess for Accenture Latvia in English, I have students from Azerbaigan, Uzbekistan, Russia and Ukraine and we use Russian as unofficial conversational language.

Because of history and current lobby of terminated living permissions in Riga almost half of speakers in Riga speak Russian. Of course, I know, that Russian of Latvian speakers is different from "Standard Russian", therefore I don't attempt to make espeak sound like that. But, I also don't want espeak sound like slang of Siberian-native "gopnik", which has learned Russian in army or prison. Therefore I think espeak should sound like "Received Russian" (similarly to "Received Pronunciation" of English), or Russian of professionally trained broadcast readers, who don't talk in slang and "eat up" consonants. Therefore I don't like, that pronunciation of e.g. "ш" and "щ" is the same, even though many speakers talk in a such way.

If there was enough support from other speakers in Russia and other Russian speaking countries, I would help to introduce different accents of Russian, but without such support from Russian speaking community it is too much effort for me.

Particularly about you comments:

> letters when typing is also pronounced incorrectly, they are short
> for example с б в ж к

What exactly do you mean by that?

> letter л is very soft.

This is known problem, and I have not changed anything, because definition of "l" is wery complicated, and making it sound properly in all combinations with other sounds requres serious effort which I can't currently afford.

**Comment by rhdunn** [comment]
The changes to Russian were made as a result of #373 (feedback on the espeak Russian pronunciations), with @valdisvi helping write the Russian rules. This is the same as Jonathan did with espeak, as he was not a native speaker of the various languages, but used feedback from native speakers (like with #373 here) and resources such as Wikipedia.

For the pronunciation of `щ`, that should be reverted. Both forms are correct<sup>[1], [2]</sup>, with the 'sch' (`[ɕː]`) form being Standard Russian, and from what I can tell 'shtch' (`[ɕt͡ɕ]`) either a conservative accent in older speakers, or a regional dialect.

For the letters, that change was made to fix when the letters are used as prepositions (e.g. https://en.wiktionary.org/wiki/%D0%B2#Etymology_2).

Thanks for reporting the pronunciation issues.

### References

1. https://en.wikipedia.org/wiki/Russian_phonology#Consonant_clusters

    > For speakers who pronounce [ɕt͡ɕ] instead of [ɕː], words like общий ('common') also constitute clusters of this type."
2. https://therussianblog.wordpress.com/2012/07/08/how-to-pronounce-russian-%D1%89-shch-sch/
    > Some resources will tell you that ‘щ‘ is pronounced as “shch”, as in “fresh cheese.” This is not correct in modern Standard Russian! Although Russian words with ‘щ‘ are transcribed as “shch” or “sch” (e.g. борщ = borsch), the pronounciation is [ɕː] nowadays. It is basically a long, palatalized version of English’s “sh” as in “ship.”

**Comment by beqabeqa473** [comment]
hi.

about letters when typing, they should sound as russian alphabet i
think or when spelling.
anyway it was as i say and it was more correct than it is now.

also about pronunciations, letters е, и ю, я with combination of other
letters such as нет, обежали называли are also incorrect
try to listen to native speakers.
unfortunately, i cannot demonstrate how it should be here in e-mails,
but most of these changes are really messed up whole use experience

On 5/1/18, Reece H. Dunn <notifications@github.com> wrote:
> The changes to Russian were made as a result of #373 (feedback on the espeak
> Russian pronunciations), with @valdisvi helping write the Russian rules.
> This is the same as Jonathan did with espeak, as he was not a native speaker
> of the various languages, but used feedback from native speakers (like with
> #373 here) and resources such as Wikipedia.
>
> For the pronunciation of `щ`, that should be reverted. Both forms are
> correct<sup>[1], [2]</sup>, with the 'sch' (`[ɕː]`) form being Standard
> Russian, and from what I can tell 'shtch' (`[ɕt͡ɕ]`) either a conservative
> accent in older speakers, or a regional dialect.
>
> For the letters, that change was made to fix when the letters are used as
> prepositions (e.g. https://en.wiktionary.org/wiki/%D0%B2#Etymology_2).
>
> Thanks for reporting the pronunciation issues.
>
> ### References
>
> 1. https://en.wikipedia.org/wiki/Russian_phonology#Consonant_clusters
>
>     > For speakers who pronounce [ɕt͡ɕ] instead of [ɕː], words like общий
> ('common') also constitute clusters of this type."
> 2.
> https://therussianblog.wordpress.com/2012/07/08/how-to-pronounce-russian-%D1%89-shch-sch/
>     > Some resources will tell you that ‘щ‘ is pronounced as “shch”, as in
> “fresh cheese.” This is not correct in modern Standard Russian! Although
> Russian words with ‘щ‘ are transcribed as “shch” or “sch” (e.g. борщ =
> borsch), the pronounciation is [ɕː] nowadays. It is basically a long,
> palatalized version of English’s “sh” as in “ship.”
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385649179


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
about е и ю я it should be because of very soft л м н

On 5/1/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> hi.
>
> about letters when typing, they should sound as russian alphabet i
> think or when spelling.
> anyway it was as i say and it was more correct than it is now.
>
> also about pronunciations, letters е, и ю, я with combination of other
> letters such as нет, обежали называли are also incorrect
> try to listen to native speakers.
> unfortunately, i cannot demonstrate how it should be here in e-mails,
> but most of these changes are really messed up whole use experience
>
> On 5/1/18, Reece H. Dunn <notifications@github.com> wrote:
>> The changes to Russian were made as a result of #373 (feedback on the
>> espeak
>> Russian pronunciations), with @valdisvi helping write the Russian rules.
>> This is the same as Jonathan did with espeak, as he was not a native
>> speaker
>> of the various languages, but used feedback from native speakers (like
>> with
>> #373 here) and resources such as Wikipedia.
>>
>> For the pronunciation of `щ`, that should be reverted. Both forms are
>> correct<sup>[1], [2]</sup>, with the 'sch' (`[ɕː]`) form being Standard
>> Russian, and from what I can tell 'shtch' (`[ɕt͡ɕ]`) either a
>> conservative
>> accent in older speakers, or a regional dialect.
>>
>> For the letters, that change was made to fix when the letters are used as
>> prepositions (e.g. https://en.wiktionary.org/wiki/%D0%B2#Etymology_2).
>>
>> Thanks for reporting the pronunciation issues.
>>
>> ### References
>>
>> 1. https://en.wikipedia.org/wiki/Russian_phonology#Consonant_clusters
>>
>>     > For speakers who pronounce [ɕt͡ɕ] instead of [ɕː], words like общий
>> ('common') also constitute clusters of this type."
>> 2.
>> https://therussianblog.wordpress.com/2012/07/08/how-to-pronounce-russian-%D1%89-shch-sch/
>>     > Some resources will tell you that ‘щ‘ is pronounced as “shch”, as
>> in
>> “fresh cheese.” This is not correct in modern Standard Russian! Although
>> Russian words with ‘щ‘ are transcribed as “shch” or “sch” (e.g. борщ =
>> borsch), the pronounciation is [ɕː] nowadays. It is basically a long,
>> palatalized version of English’s “sh” as in “ship.”
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385649179
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by valdisvi** [comment]
As default pronunciation of 'щ' I can change it either to [`SS;`](https://odo.lv/Espeak?githuburl=https%3A%2F%2Fgithub.com%2Fhozosch%2Fespeak-ng&eslang=-vru&speed=160&output=-w&debug=-x&text=%5B%5BVpSS%3B%27en%5EijI%5D%5D.&formmethod=get) or [`S;S;`](https://odo.lv/Espeak?githuburl=https%3A%2F%2Fgithub.com%2Fhozosch%2Fespeak-ng&eslang=-vru&speed=160&output=-w&debug=-x&text=%5B%5BVpS%3BS%3B%27en%5EijI%5D%5D.&formmethod=get). Which one do you prefer?

**Comment by beqabeqa473** [comment]
hi.

maybe S;S; would be better.

what was past implementation?

On 5/1/18, Valdis Vitolins <notifications@github.com> wrote:
> As default pronunciation of 'щ' I can change it either to
> [`SS;`](https://odo.lv/Espeak?githuburl=https%3A%2F%2Fgithub.com%2Fhozosch%2Fespeak-ng&eslang=-vru&speed=160&output=-w&debug=-x&text=%5B%5BVpSS%3B%27en%5EijI%5D%5D.&formmethod=get)
> or
> [`S;S;`](https://odo.lv/Espeak?githuburl=https%3A%2F%2Fgithub.com%2Fhozosch%2Fespeak-ng&eslang=-vru&speed=160&output=-w&debug=-x&text=%5B%5BVpS%3BS%3B%27en%5EijI%5D%5D.&formmethod=get).
> Which one do you prefer?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385665040


-- 
with best regards beqa

**Comment by valdisvi** [comment]
Previously I made it more distinct with `StS;`, which probably is too harsh for "normal" Russians.
To make adjustments for л, м and н eSpeak Edit is neededd, which currently is [quite hard to get running](https://github.com/valdisvi/espeak-ng-espeakedit). If it helps, I can provide compiled binary file for 46-bit Linux in this GitHub project.

**Comment by rhdunn** [comment]
щ should be reverted to `S;` like it was previously (per the second reference I mentioned -- https://therussianblog.wordpress.com/2012/07/08/how-to-pronounce-russian-%D1%89-shch-sch/). According to that, `щ` should be `ɕː` (`S;`, i.e. alveolo-palatal) and `ш` should be `ʂ` (`s.`, i.e. retroflex).

**Comment by beqabeqa473** [comment]
i don't know what is causing these artefacts, but previously it was
acceptable to hear нет, обежали, называли меня but not now.

On 5/1/18, Reece H. Dunn <notifications@github.com> wrote:
> щ should be reverted to `S;` like it was previously (per the second
> reference I mentioned --
> https://therussianblog.wordpress.com/2012/07/08/how-to-pronounce-russian-%D1%89-shch-sch/).
> According to that, `щ` should be `ɕː` (`S;`, i.e. alveolo-palatal) and `ш`
> should be `ʂ` (`s.`, i.e. retroflex).
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385667415


-- 
with best regards beqa

**Comment by valdisvi** [comment]
Currently eSpeak NG uses `S` or `Z` for both **ш** and **щ**, which is not very precise.
From standardization prospective we could use `s.` for **ш** and `S;S;` (or `SS;`) for **щ** e.g. as for [шить щит](https://odo.lv/Espeak?githuburl=https%3A%2F%2Fgithub.com%2Fhozosch%2Fespeak-ng&eslang=-vru&speed=160&output=-w&debug=-x&text=%5B%5Bs.%27yt%3B+S%3BS%3B%27it%5D%5D&formmethod=get) but current `s.` sounds too soft even for me.
If we use `s.` and `S`, then again, definition of `s.` should be adjusted for Russian.

**Comment by valdisvi** [comment]
beqabeqa473, Reece reverted pronunciation of **щ** back to `S;`, but (for me), this sounds too short. Especially where **щ** is at the end of word, e.g. [борщ](https://odo.lv/Espeak?&eslang=-vru&speed=160&output=-w&debug=-x&text=%D0%B1%D0%BE%D1%80%D1%89&formmethod=get). Some compromise could be just longer `S;` or `S;S;` at the end of word.

**Comment by rhdunn** [comment]
I have reverted the `щ` change to what it was previously. Technically, it should be `S;:` (not `SS;` or `S;S;`, per https://en.wiktionary.org/wiki/%D1%89%D1%91%D1%82%D0%BA%D0%B0#Russian), but neither of these sounds right to me -- the lengthened `S;` likely needs adjusting.

I have also fixed the letter variants of the single-letter particles.

Regarding words like "нет" and "небо" (https://en.wiktionary.org/wiki/%D0%BD%D0%B5%D0%B1%D0%BE#Russian), the thing you are referencing is the "y" sound in words like "yes" (hence the made up "гонет" sounds like "gone yet"). Specifically, it is using the sound used in Spanish "ñ" (e.g. "piña"). The espeak version pronounces "нет" like "net", which is wrong. The `n;` transcription would be a better transcription, but the generic palatalisation behaviour sounds like 'n' to me.

The other words have a similar issue -- the "y" off-glide (palatalisation) is not pronounced enough.

**Comment by beqabeqa473** [comment]
the щ is ok for me.

On 5/1/18, Reece H. Dunn <notifications@github.com> wrote:
> I have reverted the `щ` change to what it was previously. Technically, it
> should be `S;:` (not `SS;` or `S;S;`, per
> https://en.wiktionary.org/wiki/%D1%89%D1%91%D1%82%D0%BA%D0%B0#Russian), but
> neither of these sounds right to me -- the lengthened `S;` likely needs
> adjusting.
>
> I have also fixed the letter variants of the single-letter particles.
>
> Regarding words like "нет" and "небо"
> (https://en.wiktionary.org/wiki/%D0%BD%D0%B5%D0%B1%D0%BE#Russian), the thing
> you are referencing is the "y" sound in words like "yes" (hence the made up
> "гонет" sounds like "gone yet"). Specifically, it is using the sound used in
> Spanish "ñ" (e.g. "piña"). The espeak version pronounces "нет" like "net",
> which is wrong. The `n;` transcription would be a better transcription, but
> the generic palatalisation behaviour sounds like 'n' to me.
>
> The other words have a similar issue -- the "y" off-glide (palatalisation)
> is not pronounced enough.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385753883


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
hi.

i don't understand what can be done with небо лево

letter л is very soft.
it was ok earlier.

On 5/1/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> the щ is ok for me.
>
> On 5/1/18, Reece H. Dunn <notifications@github.com> wrote:
>> I have reverted the `щ` change to what it was previously. Technically, it
>> should be `S;:` (not `SS;` or `S;S;`, per
>> https://en.wiktionary.org/wiki/%D1%89%D1%91%D1%82%D0%BA%D0%B0#Russian),
>> but
>> neither of these sounds right to me -- the lengthened `S;` likely needs
>> adjusting.
>>
>> I have also fixed the letter variants of the single-letter particles.
>>
>> Regarding words like "нет" and "небо"
>> (https://en.wiktionary.org/wiki/%D0%BD%D0%B5%D0%B1%D0%BE#Russian), the
>> thing
>> you are referencing is the "y" sound in words like "yes" (hence the made
>> up
>> "гонет" sounds like "gone yet"). Specifically, it is using the sound used
>> in
>> Spanish "ñ" (e.g. "piña"). The espeak version pronounces "нет" like
>> "net",
>> which is wrong. The `n;` transcription would be a better transcription,
>> but
>> the generic palatalisation behaviour sounds like 'n' to me.
>>
>> The other words have a similar issue -- the "y" off-glide
>> (palatalisation)
>> is not pronounced enough.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-385753883
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by valdisvi** [comment]
beqabeqa473, does this variant of [небо лево](https://odo.lv/Espeak?eslang=-vru&output=-w&text=[[n%3B%27ebV+l%3B%27evV]]) sounds better?

**Comment by beqabeqa473** [comment]
yes, it is better than it is currently.

On 5/2/18, Valdis Vitolins <notifications@github.com> wrote:
> beqabeqa473, does this variant of [небо
> лево](https://odo.lv/Espeak?eslang=-vru&output=-w&text=[[n%3B%27ebV+l%3B%27evV]])
> sounds better?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386034060


-- 
with best regards beqa

**Comment by valdisvi** [comment]
Beqa, issues, which we could fix without adjustments of phoneme definitions, are now solved in [development version](https://odo.lv/Espeak) of espeak-ng. With current rules I don't like, that **няня** now is spelled with too distinct **nj** `[[n;'An;V]]`. For me more appropriate feels `[[n^'An^V]]` with softer **n** similarly to [GoogleTranslate](https://translate.google.com/#ru/lv/%D0%BD%D1%8F%D0%BD%D1%8F). You can listen both variants [here](https://odo.lv/Espeak?eslang=-vru&output=-w&debug=-x&text=няня.%0D%0A[[n%3B'An%3BV]].%0D%0A[[n^'An^V]].).

**Comment by beqabeqa473** [comment]
hi.

with the latest master, combination of letters with л м н ois not fixed.

i must say once again, it is not correct to soften these letters in
russian language.

please, revert it as it was before.

it should not pronounced as не - нье нет ли - льи лю - лью ле - лье.

it is not possible to read seriously something with these changes.

On 5/2/18, Valdis Vitolins <notifications@github.com> wrote:
> Beqa, issues, which we could fix without adjustments of phoneme definitions,
> are now solved in [development version](https://odo.lv/Espeak) of espeak-ng.
> With current rules I don't like, that **няня** now is spelled with too
> distinct **nj** `[[n;'An;V]]`. For me more appropriate feels `[[n^'An^V]]`
> with softer **n** similarly to
> [GoogleTranslate](https://translate.google.com/#ru/lv/%D0%BD%D1%8F%D0%BD%D1%8F).
> You can listen both variants
> [here](https://odo.lv/Espeak?eslang=-vru&output=-w&debug=-x&text=няня.%0D%0A[[n%3B'An%3BV]].%0D%0A[[n^'An^V]].).
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386089558


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
it doesn't matter for me how you like it.
maybe in latvia there is a separate accent of russian, but this
doesn't mean that it is correct.

i am using russian language as my primary language every day and i
know how words and letters should be pronounced.

On 5/3/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> hi.
>
> with the latest master, combination of letters with л м н ois not fixed.
>
> i must say once again, it is not correct to soften these letters in
> russian language.
>
> please, revert it as it was before.
>
> it should not pronounced as не - нье нет ли - льи лю - лью ле - лье.
>
> it is not possible to read seriously something with these changes.
>
> On 5/2/18, Valdis Vitolins <notifications@github.com> wrote:
>> Beqa, issues, which we could fix without adjustments of phoneme
>> definitions,
>> are now solved in [development version](https://odo.lv/Espeak) of
>> espeak-ng.
>> With current rules I don't like, that **няня** now is spelled with too
>> distinct **nj** `[[n;'An;V]]`. For me more appropriate feels
>> `[[n^'An^V]]`
>> with softer **n** similarly to
>> [GoogleTranslate](https://translate.google.com/#ru/lv/%D0%BD%D1%8F%D0%BD%D1%8F).
>> You can listen both variants
>> [here](https://odo.lv/Espeak?eslang=-vru&output=-w&debug=-x&text=няня.%0D%0A[[n%3B'An%3BV]].%0D%0A[[n^'An^V]].).
>>
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386089558
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
we already have letters such as е ё ю я we don't need additional ль мь
нь and so on.

On 5/3/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> it doesn't matter for me how you like it.
> maybe in latvia there is a separate accent of russian, but this
> doesn't mean that it is correct.
>
> i am using russian language as my primary language every day and i
> know how words and letters should be pronounced.
>
> On 5/3/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
>> hi.
>>
>> with the latest master, combination of letters with л м н ois not fixed.
>>
>> i must say once again, it is not correct to soften these letters in
>> russian language.
>>
>> please, revert it as it was before.
>>
>> it should not pronounced as не - нье нет ли - льи лю - лью ле - лье.
>>
>> it is not possible to read seriously something with these changes.
>>
>> On 5/2/18, Valdis Vitolins <notifications@github.com> wrote:
>>> Beqa, issues, which we could fix without adjustments of phoneme
>>> definitions,
>>> are now solved in [development version](https://odo.lv/Espeak) of
>>> espeak-ng.
>>> With current rules I don't like, that **няня** now is spelled with too
>>> distinct **nj** `[[n;'An;V]]`. For me more appropriate feels
>>> `[[n^'An^V]]`
>>> with softer **n** similarly to
>>> [GoogleTranslate](https://translate.google.com/#ru/lv/%D0%BD%D1%8F%D0%BD%D1%8F).
>>> You can listen both variants
>>> [here](https://odo.lv/Espeak?eslang=-vru&output=-w&debug=-x&text=няня.%0D%0A[[n%3B'An%3BV]].%0D%0A[[n^'An^V]].).
>>>
>>>
>>> --
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386089558
>>
>>
>> --
>> with best regards beqa
>>
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by rhdunn** [comment]
@beqabeqa473 [нет](https://en.wiktionary.org/wiki/%D0%BD%D0%B5%D1%82) is described there as using a 'y' off-glide (palatalisation) -- the audio pronounces it that way, and not like "net". The entry for [nyet](https://en.wiktionary.org/wiki/nyet) references the Cyrillic нет in Russian, not ньет. This is therefore the correct Russian transcription. Also, Wikipedia's [Russian phonology](https://en.wikipedia.org/wiki/Russian_phonology) has many examples of this pronunciation for не with audio from Russian speakers.

**Comment by beqabeqa473** [comment]
yes, you are saying correctly.

i also say that л м н should be without ь which softens word
not ньет but нет
not льево but лево
not ньянья but няня

also letter я is somehow changed and it sounds like ya written in latin.

On 5/3/18, Reece H. Dunn <notifications@github.com> wrote:
> To further clarify -- this is using `n;` for the palatalisation, not `n^`.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386377652


-- 
with best regards beqa

**Comment by valdisvi** [comment]
Thanks to international nature of Accenture's recruitment, I recorded [sample of different Russian accents](https://odo.lv/ftp/temp/Russian_sample.oga) during last Java Bootcamp. In most of them consonants are softened before soft vowels.

**Comment by beqabeqa473** [comment]
yes, and first of all, most of them are not native russians, secondly,
they don't say ньянья and льена how now espeak is working.

it should be softend a bit but consonant should not be separated from
a vowel as you are doing now.

you can listen to a rhvoice. it is a ttts developed by native russian
speaker and you will see a difference.


On 5/4/18, Valdis Vitolins <notifications@github.com> wrote:
> Thanks to international nature of Accenture's recruitment, I recorded
> [sample of different Russian
> accents](https://odo.lv/ftp/temp/Russian_sample.oga) during last Java
> Bootcamp. In most of them consonants are softened before soft vowels.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386638517


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
and yes, soft vowels are for softenning word and we don't need
additional soft consonant.

show me a phonetic rule in russian language where this is written.

On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> yes, and first of all, most of them are not native russians, secondly,
> they don't say ньянья and льена how now espeak is working.
>
> it should be softend a bit but consonant should not be separated from
> a vowel as you are doing now.
>
> you can listen to a rhvoice. it is a ttts developed by native russian
> speaker and you will see a difference.
>
>
> On 5/4/18, Valdis Vitolins <notifications@github.com> wrote:
>> Thanks to international nature of Accenture's recruitment, I recorded
>> [sample of different Russian
>> accents](https://odo.lv/ftp/temp/Russian_sample.oga) during last Java
>> Bootcamp. In most of them consonants are softened before soft vowels.
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386638517
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
the most correct pronunciation was by anna, dasha and maybe natalya from irkutsk

On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> and yes, soft vowels are for softenning word and we don't need
> additional soft consonant.
>
> show me a phonetic rule in russian language where this is written.
>
> On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
>> yes, and first of all, most of them are not native russians, secondly,
>> they don't say ньянья and льена how now espeak is working.
>>
>> it should be softend a bit but consonant should not be separated from
>> a vowel as you are doing now.
>>
>> you can listen to a rhvoice. it is a ttts developed by native russian
>> speaker and you will see a difference.
>>
>>
>> On 5/4/18, Valdis Vitolins <notifications@github.com> wrote:
>>> Thanks to international nature of Accenture's recruitment, I recorded
>>> [sample of different Russian
>>> accents](https://odo.lv/ftp/temp/Russian_sample.oga) during last Java
>>> Bootcamp. In most of them consonants are softened before soft vowels.
>>>
>>> --
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386638517
>>
>>
>> --
>> with best regards beqa
>>
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by beqabeqa473** [comment]
and more, you recorded most of latvian people.
of course latvians have a different accent of russian not as it is in russia.
secondly, Azerbaijanians were absolutely wrong in pronunciation.
i will say once again. if you want espeak to be sounded with latvian
accent, make another variant.
we don't need these latvian rules in russian voice.

On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> the most correct pronunciation was by anna, dasha and maybe natalya from
> irkutsk
>
> On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
>> and yes, soft vowels are for softenning word and we don't need
>> additional soft consonant.
>>
>> show me a phonetic rule in russian language where this is written.
>>
>> On 5/4/18, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
>>> yes, and first of all, most of them are not native russians, secondly,
>>> they don't say ньянья and льена how now espeak is working.
>>>
>>> it should be softend a bit but consonant should not be separated from
>>> a vowel as you are doing now.
>>>
>>> you can listen to a rhvoice. it is a ttts developed by native russian
>>> speaker and you will see a difference.
>>>
>>>
>>> On 5/4/18, Valdis Vitolins <notifications@github.com> wrote:
>>>> Thanks to international nature of Accenture's recruitment, I recorded
>>>> [sample of different Russian
>>>> accents](https://odo.lv/ftp/temp/Russian_sample.oga) during last Java
>>>> Bootcamp. In most of them consonants are softened before soft vowels.
>>>>
>>>> --
>>>> You are receiving this because you were mentioned.
>>>> Reply to this email directly or view it on GitHub:
>>>> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386638517
>>>
>>>
>>> --
>>> with best regards beqa
>>>
>>
>>
>> --
>> with best regards beqa
>>
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by valdisvi** [comment]
With the latest commit 82214e80cfc7bd929c455102005db9c691d5c2ff I reverted "too soft" 'л' and 'н' to palatalized, by adding short `y` sound (written as `;` in phonetic output of espeak-ng) after these consonants.
But, as I [told earlier](#issuecomment-386089558), without adjustments of [phoneme definitions](https://github.com/espeak-ng/espeak-ng/blob/master/phsource/ph_russian), you can't get "slight" softening of consonant without adding anything between it and following vowel, simply because there are no such sounds defined in espeak-ng.
Coming here, to say that you like [another tool](https://github.com/Olga-Yakovleva/RHVoice) better, is not nice. Instead of criticizing you can contribute to espeak-ng. You can [start from here](https://github.com/espeak-ng/espeak-ng/issues/291#issuecomment-318858261), then [read Espeak Online Guide](https://odo.lv/EspeakGuide) and to change phoneme definitions, you can use [eSpeakEdit from here.](https://github.com/valdisvi/espeak-ng-espeakedit)

**Comment by hozosch** [comment]
Even though I don't speak russian at all, I tested rh voice due to my language curiosity and espeak really sounds weird to me compared to rh voice. Ю sounds rather weird to me in espeak, actually rather like the british u sound. The only sound in russian I can compare to english, at least in RH voice, is the l.

**Comment by valdisvi** [comment]
In my non-native-Russian opinion, unknown previous contributor, who submitted data to Jonathan was too obsessed with hard vowels, therefore espeak-ng speaks Russian with "hard i everywhere".

**Comment by hozosch** [comment]
What really baffles me is how espeak pronounces the number 5 in russian. All the other synths I heard didn't say it like that, they said it more with a short e kind of sound.

**Comment by beqabeqa473** [comment]
i am not saying to improve something
i am just saying to revert things as they were before, because they
were more correct than now
i don't say that previous rules were absolutely right, but they were
better than it is now.
you didn't revert л н because even with the latest commit it says
льево, not лево.

On 5/4/18, hozosch <notifications@github.com> wrote:
> What really baffles me is how espeak pronounces the number 5 in russian. All
> the other synths I heard didn't say it like that, they said it more with a
> short e kind of sound.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/espeak-ng/espeak-ng/issues/474#issuecomment-386659769


-- 
with best regards beqa
